#! /usr/bin/env bash

# Local file
if [ -f "$1" ]; then
  openssl x509 -in "$1" -noout -text
  exit
fi

# URL
if [ -n "$1" ]; then
  echo |
  openssl s_client -connect "$1":443 2> /dev/null |
  openssl x509 -noout -text
  exit
fi

# Piped in
cat /dev/stdin | openssl x509 -noout -text